### ISSUE TITLE
Please upgrade serial-port dependency

### ISSUE THREAD

**Issue by basvdijk** [ruudverheijden/node-p1-reader#11]
Latest version is 6.2.0, in the package.json is still referred to 4.*

**Comment by ruudverheijden** [comment]
Done!

**Comment by JeromeGillard** [comment]
Note for my future self: `serialport@12.0.0`  prebuilt binaries for RaspberryPi causes Segmentation Faults.  
Rebuilding the bindings solved the issue.  

See https://github.com/serialport/node-serialport/issues/2438#issuecomment-2416343649
