### ISSUE TITLE
calculate Voltage and resistance

### ISSUE THREAD

**Issue by timoline** [ruudverheijden/node-p1-reader#13]
maybe a nice to have is to calculate Voltage and resistance

**Comment by ruudverheijden** [comment]
Yes I agree that would be nice. However, my physics classes where a long time ago... :( Can you provide me the calculations?

**Comment by timoline** [comment]
its a long time ago for me too:-)

here you go...
https://www.esdsite.nl/elektronica/formules/wetvanohm.html

**Comment by timoline** [comment]
close
