### ISSUE TITLE
emit raw data

### ISSUE THREAD

**Issue by timoline** [ruudverheijden/node-p1-reader#3]
Is it possible you add the possibility to get the raw data?

`constructor.emit('raw', Packet);`

**Comment by ruudverheijden** [comment]
Sure! I'm quite busy next few days so I will have time end of the week to fix it. Or you can send me a pull request ;)

**Comment by ruudverheijden** [comment]
The feature has been added in version 1.4.0, which is now released.

**Comment by timoline** [comment]
great thx
